name: Snyk Python

on:
  push:
    branches: ["main", "dev", "snyk"]
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}